### PR TITLE
Consumer prints number of received messages

### PR DESCRIPTION
**Pull request by michalxo**
Signed-off-by: Michal Tóth <mtoth@redhat.com>

```
2021-02-24 12:37:17 INFO  KafkaConsumerExample:47 - Received message:
2021-02-24 12:37:17 INFO  KafkaConsumerExample:48 - 	partition: 0
2021-02-24 12:37:17 INFO  KafkaConsumerExample:49 - 	offset: 498
2021-02-24 12:37:17 INFO  KafkaConsumerExample:50 - 	value: "Hello world - 98"
2021-02-24 12:37:17 INFO  KafkaConsumerExample:52 - 	headers:
2021-02-24 12:37:17 INFO  KafkaConsumerExample:47 - Received message:
2021-02-24 12:37:17 INFO  KafkaConsumerExample:48 - 	partition: 0
2021-02-24 12:37:17 INFO  KafkaConsumerExample:49 - 	offset: 499
2021-02-24 12:37:17 INFO  KafkaConsumerExample:50 - 	value: "Hello world - 99"
2021-02-24 12:37:17 INFO  KafkaConsumerExample:52 - 	headers:
2021-02-24 12:37:17 INFO  KafkaConsumerExample:63 - Received 500 messages
[2021-02-24T12:37:17.446+0000] Heap
[2021-02-24T12:37:17.446+0000]  def new generation   total 72512K, used 37351K [0x0000000715600000, 0x000000071a4a0000, 0x0000000763950000)
[2021-02-24T12:37:17.446+0000]   eden space 64512K,  48% used [0x0000000715600000, 0x000000071749a350, 0x0000000719500000)
```

### CODE REVIEW

**Review by sknot-rh — APPROVED** [review]

**Review by Frawless — APPROVED** [review]
Just out of curiosity, why do you need this?

**Review by im-konge — APPROVED** [review]

**Review by ppatierno — APPROVED** [review]

**Comment by michalxo** [comment]
> Just out of curiosity, why do you need this?

To see the real number of consumed messages. Example of usage is with MirrorMaker2 and reading/checking offsets, where consumer left reading on source cluster and should continue to read "the rest" of message from target/mirrored cluster.

**Comment by Frawless** [comment]
well it will always print the expected number of messages, otherwise, the loop will continue forever...or I miss something?

**Comment by michalxo** [comment]
> well it will always print the expected number of messages, otherwise, the loop will continue forever...or I miss something?

It prints received # of msgs, which it does.

**Pull request merged**
